// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjxvjqfhgxdybpvqvqka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqeHZqcWZoZ3hkeWJwdnF2cWthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTMyOTgsImV4cCI6MjA2NTU4OTI5OH0.LzXAcyR7PEPk_k5sUc2JjyKb6ACjBc0hgiYk39oqSu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);